### ISSUE TITLE
Prediction code

### ISSUE THREAD

**Issue by PSSubramanya** [Yoan-D/exploring-text-to-image-synthesis-with-conditional-GANs#4]
could you provide the prediction code .

**Comment by GrepRunRepeat** [comment]
Hi PSSubramanya,

the third last code snippet in the following notebook shows you how to make predictions:
https://github.com/Yoan-D/text-to-image-synthesis/blob/master/Text2Image_GAN_MS.ipynb

**Comment by PSSubramanya** [comment]
thank you.
